In [1]:
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Dropout
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [2]:
#載入資料
df = pd.read_csv('./output4.csv', encoding='utf-8')
df

class  thumb_CmcX  thumb_CmcY  thumb_CmcZ  thumb_McpX  thumb_McpY  \
0          0    0.013346   -0.078824   -0.093423    0.031121   -0.122133   
1          0    0.027224   -0.044876   -0.043898    0.058716   -0.081201   
2          0   -0.003453    0.058013   -0.038275    0.007701    0.082564   
3          0    0.011858   -0.065664   -0.090578    0.034992   -0.107807   
4          0    0.024853   -0.048601   -0.048028    0.050411   -0.086527   
...      ...         ...         ...         ...         ...         ...   
35170      4    0.092155   -0.072534   -0.064873    0.224030   -0.116162   
35171      4    0.092424   -0.073813   -0.064069    0.225228   -0.118873   
35172      4    0.097000   -0.064246   -0.076335    0.230042   -0.105550   
35173      4    0.100859   -0.063578   -0.075059    0.233116   -0.103082   
35174      4    0.098224   -0.066448   -0.072397    0.233586   -0.104373   

       thumb_McpZ  thumb_IpX  thumb_IpY  thumb_IpZ  ...  pinky_McpZ  \
0       -0.160828   0.008913  -0.113420  -0.211022  ...   -0.146264   
1       -0.078251   0.055767  -0.074666  -0.108053  ...   -0.089761   
2       -0.066121   0.003853   0.067236  -0.087953  ...   -0.064716   
3       -0.156370   0.007863  -0.092267  -0.208585  ...   -0.136011   
4       -0.089649   0.039719  -0.073551  -0.126198  ...   -0.110127   
...           ...        ...        ...        ...  ...         ...   
35170   -0.068147   0.343033  -0.115294  -0.065577  ...    0.088988   
35171   -0.067604   0.344341  -0.116408  -0.065691  ...    0.084817   
35172   -0.082055   0.348379  -0.105353  -0.079992  ...    0.102595   
35173   -0.080414   0.350211  -0.102614  -0.078176  ...    0.104006   
35174   -0.077202   0.350857  -0.101643  -0.075379  ...    0.099498   

       pinky_PipX  pinky_PipY  pinky_PipZ  pinky_DipX  pinky_DipY  pinky_DipZ  \
0       -0.093332    0.077454   -0.197066   -0.100144    0.039600   -0.197679   
1       -0.011452    0.085340   -0.123443   -0.016239    0.053635   -0.115443   
2        0.008161   -0.042829   -0.089203   -0.002254   -0.042870   -0.089281   
3       -0.061092    0.088679   -0.195662   -0.074918    0.046089   -0.193745   
4       -0.028435    0.078580   -0.158202   -0.026730    0.049350   -0.147598   
...           ...         ...         ...         ...         ...         ...   
35170    0.306037    0.071159    0.065973    0.288056    0.080720    0.044411   
35171    0.311503    0.071365    0.058307    0.291183    0.078983    0.036301   
35172    0.317471    0.070517    0.072401    0.308306    0.085774    0.039162   
35173    0.320064    0.072447    0.077781    0.313789    0.085835    0.045871   
35174    0.319386    0.074944    0.071577    0.312857    0.088435    0.037308   

       pinky_TipX  pinky_TipY  pinky_TipZ  
0       -0.074212    0.029099   -0.192775  
1        0.009828    0.048981   -0.101101  
2        0.021662   -0.038748   -0.085531  
3       -0.055045    0.027574   -0.181527  
4        0.008735    0.047540   -0.126619  
...           ...         ...         ...  
35170    0.249058    0.089427    0.034287  
35171    0.249589    0.085530    0.026626  
35172    0.265045    0.101793    0.021297  
35173    0.272907    0.100060    0.028143  
35174    0.268381    0.101102    0.017385  

[35175 rows x 61 columns]

In [3]:
#取標籤
label = df["class"]
label

0        0
1        0
2        0
3        0
4        0
        ..
35170    4
35171    4
35172    4
35173    4
35174    4
Name: class, Length: 35175, dtype: int64

In [4]:
#取出特徵
data = df.iloc[:,1:]
data

thumb_CmcX  thumb_CmcY  thumb_CmcZ  thumb_McpX  thumb_McpY  thumb_McpZ  \
0        0.013346   -0.078824   -0.093423    0.031121   -0.122133   -0.160828   
1        0.027224   -0.044876   -0.043898    0.058716   -0.081201   -0.078251   
2       -0.003453    0.058013   -0.038275    0.007701    0.082564   -0.066121   
3        0.011858   -0.065664   -0.090578    0.034992   -0.107807   -0.156370   
4        0.024853   -0.048601   -0.048028    0.050411   -0.086527   -0.089649   
...           ...         ...         ...         ...         ...         ...   
35170    0.092155   -0.072534   -0.064873    0.224030   -0.116162   -0.068147   
35171    0.092424   -0.073813   -0.064069    0.225228   -0.118873   -0.067604   
35172    0.097000   -0.064246   -0.076335    0.230042   -0.105550   -0.082055   
35173    0.100859   -0.063578   -0.075059    0.233116   -0.103082   -0.080414   
35174    0.098224   -0.066448   -0.072397    0.233586   -0.104373   -0.077202   

       thumb_IpX  thumb_IpY  thumb_IpZ  thumb_TipX  ...  pinky_McpZ  \
0       0.008913  -0.113420  -0.211022   -0.008307  ...   -0.146264   
1       0.055767  -0.074666  -0.108053    0.056937  ...   -0.089761   
2       0.003853   0.067236  -0.087953   -0.004198  ...   -0.064716   
3       0.007863  -0.092267  -0.208585   -0.020125  ...   -0.136011   
4       0.039719  -0.073551  -0.126198    0.039590  ...   -0.110127   
...          ...        ...        ...         ...  ...         ...   
35170   0.343033  -0.115294  -0.065577    0.421387  ...    0.088988   
35171   0.344341  -0.116408  -0.065691    0.422458  ...    0.084817   
35172   0.348379  -0.105353  -0.079992    0.431348  ...    0.102595   
35173   0.350211  -0.102614  -0.078176    0.432410  ...    0.104006   
35174   0.350857  -0.101643  -0.075379    0.432598  ...    0.099498   

       pinky_PipX  pinky_PipY  pinky_PipZ  pinky_DipX  pinky_DipY  pinky_DipZ  \
0       -0.093332    0.077454   -0.197066   -0.100144    0.039600   -0.197679   
1       -0.011452    0.085340   -0.123443   -0.016239    0.053635   -0.115443   
2        0.008161   -0.042829   -0.089203   -0.002254   -0.042870   -0.089281   
3       -0.061092    0.088679   -0.195662   -0.074918    0.046089   -0.193745   
4       -0.028435    0.078580   -0.158202   -0.026730    0.049350   -0.147598   
...           ...         ...         ...         ...         ...         ...   
35170    0.306037    0.071159    0.065973    0.288056    0.080720    0.044411   
35171    0.311503    0.071365    0.058307    0.291183    0.078983    0.036301   
35172    0.317471    0.070517    0.072401    0.308306    0.085774    0.039162   
35173    0.320064    0.072447    0.077781    0.313789    0.085835    0.045871   
35174    0.319386    0.074944    0.071577    0.312857    0.088435    0.037308   

       pinky_TipX  pinky_TipY  pinky_TipZ  
0       -0.074212    0.029099   -0.192775  
1        0.009828    0.048981   -0.101101  
2        0.021662   -0.038748   -0.085531  
3       -0.055045    0.027574   -0.181527  
4        0.008735    0.047540   -0.126619  
...           ...         ...         ...  
35170    0.249058    0.089427    0.034287  
35171    0.249589    0.085530    0.026626  
35172    0.265045    0.101793    0.021297  
35173    0.272907    0.100060    0.028143  
35174    0.268381    0.101102    0.017385  

[35175 rows x 60 columns]

In [5]:
#資料標準化
scaler = MinMaxScaler(feature_range=(0,1))
data = scaler.fit_transform(data)
data

array([[0.33491464, 0.26630759, 0.45434197, ..., 0.16665435, 0.38666852,
        0.29415368],
       [0.36809042, 0.34334404, 0.57089326, ..., 0.24330855, 0.40791601,
        0.39886017],
       [0.29475638, 0.57682389, 0.58412454, ..., 0.25410258, 0.31415974,
        0.41664353],
       ...,
       [0.53489518, 0.29938935, 0.49455718, ..., 0.47609701, 0.46435606,
        0.53865897],
       [0.54412092, 0.30090545, 0.49755907, ..., 0.48326747, 0.46250445,
        0.54647822],
       [0.53782053, 0.29439227, 0.5038242 , ..., 0.47913894, 0.46361785,
        0.53419002]])

In [6]:
#分割資料
#把資料轉numpy
reshaped_data = np.array(data)
reshaped_label = np.array(label)
#將資料分為8:2

train_feature, test_feature, train_label, test_label = train_test_split(reshaped_data, reshaped_label, test_size=0.2, random_state = 42)

# split_boundary = int(reshaped_data.shape[0]*0.8)
# train_feature = reshaped_data[: split_boundary]
# test_feature = reshaped_data[split_boundary:]
# train_label = reshaped_label[: split_boundary]
# test_label = reshaped_label[split_boundary:]
print("測試資料:", train_feature)
print("訓練資料:", test_feature)
print("測試資料數量:", len(train_feature))
print("訓練資料數量:", len(test_feature))
print("測試資料維度:", train_feature.shape)
print("訓練資料維度:", test_feature.shape)

測試資料: [[0.46655521 0.27316622 0.49060881 ... 0.54755772 0.51457682 0.34656982]
 [0.46991208 0.2830262  0.41828866 ... 0.56254123 0.62847227 0.27107901]
 [0.52985994 0.27104863 0.53511561 ... 0.4463691  0.44756778 0.53191852]
 ...
 [0.65356114 0.1971388  0.12104609 ... 0.57148556 0.46722833 0.61368302]
 [0.35817674 0.13653056 0.5552167  ... 0.39553211 0.42298085 0.50577061]
 [0.50529136 0.35642233 0.35081243 ... 0.54789196 0.61263298 0.38114183]]
訓練資料: [[0.39303459 0.12641832 0.54605795 ... 0.40153258 0.42388206 0.52029635]
 [0.34434144 0.53728441 0.64695326 ... 0.19899786 0.36692841 0.50654403]
 [0.33774823 0.69259966 0.36179473 ... 0.47923365 0.69535702 0.50913134]
 ...
 [0.28577672 0.55548793 0.59935464 ... 0.233814   0.58717824 0.44248859]
 [0.42313789 0.30328733 0.45316646 ... 0.46712262 0.45774031 0.38971262]
 [0.44814882 0.07835912 0.52684568 ... 0.44279978 0.41477045 0.48843547]]
測試資料數量: 28140
訓練資料數量: 7035
測試資料維度: (28140, 60)
訓練資料維度: (7035, 60)


In [7]:
train_label = np_utils.to_categorical(train_label)
test_label= np_utils.to_categorical(test_label)
print("訓練標籤:",train_label.shape)
print("測試標籤:",test_label.shape)

訓練標籤: (28140, 5)
測試標籤: (7035, 5)


In [8]:
#更改資料維度
train_feature = np.reshape(train_feature, (train_feature.shape[0], train_feature.shape[1], 1))
test_feature = np.reshape(test_feature, (test_feature.shape[0], test_feature.shape[1], 1))
print("測試資料維度:", train_feature.shape)
print("訓練資料維度:", test_feature.shape)

測試資料維度: (28140, 60, 1)
訓練資料維度: (7035, 60, 1)


In [9]:
#訓練模型
model = Sequential()
n = 0.2
model.add(Dense(units=32, input_dim=60, activation='relu'))    #輸入60個特徵
model.add(Dropout(n))
model.add(Dense(units=64, activation='relu'))
model.add(Dropout(n))
model.add(Dense(units=128, activation='relu'))
model.add(Dropout(n))
model.add(Dense(units=256, activation='relu'))
model.add(Dropout(n))
model.add(Dense(units=5, activation='softmax'))   #輸出為5個分類
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                1952      
                                                                 
 dropout (Dropout)           (None, 32)                0         
                                                                 
 dense_1 (Dense)             (None, 64)                2112      
                                                                 
 dropout_1 (Dropout)         (None, 64)                0         
                                                                 
 dense_2 (Dense)             (None, 128)               8320      
                                                                 
 dropout_2 (Dropout)         (None, 128)               0         
                                                                 
 dense_3 (Dense)             (None, 256)               3

In [10]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
fitmodel = model.fit(x=train_feature, y=train_label, validation_split=0.2, epochs=40, batch_size=20, verbose=2)
score = model.evaluate(x=test_feature, y=test_label, verbose=2)
print('\n測試資料準確率:', score[1])

Epoch 1/40
1126/1126 - 8s - loss: 0.8269 - accuracy: 0.6332 - val_loss: 0.5194 - val_accuracy: 0.7859 - 8s/epoch - 7ms/step
Epoch 2/40
1126/1126 - 5s - loss: 0.5494 - accuracy: 0.7762 - val_loss: 0.3768 - val_accuracy: 0.8701 - 5s/epoch - 5ms/step
Epoch 3/40
1126/1126 - 5s - loss: 0.4598 - accuracy: 0.8225 - val_loss: 0.3383 - val_accuracy: 0.8826 - 5s/epoch - 5ms/step
Epoch 4/40
1126/1126 - 7s - loss: 0.4042 - accuracy: 0.8486 - val_loss: 0.2446 - val_accuracy: 0.9213 - 7s/epoch - 6ms/step
Epoch 5/40
1126/1126 - 8s - loss: 0.3596 - accuracy: 0.8663 - val_loss: 0.2070 - val_accuracy: 0.9323 - 8s/epoch - 7ms/step
Epoch 6/40
1126/1126 - 8s - loss: 0.3298 - accuracy: 0.8806 - val_loss: 0.2627 - val_accuracy: 0.8955 - 8s/epoch - 7ms/step
Epoch 7/40
1126/1126 - 8s - loss: 0.3211 - accuracy: 0.8857 - val_loss: 0.1991 - val_accuracy: 0.9312 - 8s/epoch - 7ms/step
Epoch 8/40
1126/1126 - 9s - loss: 0.2889 - accuracy: 0.8961 - val_loss: 0.1892 - val_accuracy: 0.9455 - 9s/epoch - 8ms/step
Epoch 9/