In [1]:
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Dropout
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [2]:
#載入資料
df = pd.read_csv('./totol_1output.csv', encoding='utf-8')
df

class  thumb_CmcX  thumb_CmcY  thumb_CmcZ  thumb_McpX  thumb_McpY  \
0          0    0.012261   -0.054713   -0.064790    0.046395   -0.081590   
1          0    0.007954    0.036694   -0.046014    0.047087    0.081199   
2          0    0.027219   -0.034373   -0.038773    0.057681   -0.044289   
3          0    0.000680   -0.036950   -0.039803    0.003148   -0.064025   
4          0   -0.016134    0.008927   -0.033502   -0.027797    0.014595   
...      ...         ...         ...         ...         ...         ...   
67799      4    0.010705   -0.060853   -0.083056    0.061441   -0.111522   
67800      4    0.016457   -0.060712   -0.078067    0.070719   -0.108737   
67801      4    0.019741   -0.062684   -0.082820    0.080508   -0.111906   
67802      4    0.027326   -0.065210   -0.071695    0.092318   -0.112928   
67803      4    0.029301   -0.069099   -0.064884    0.096214   -0.119432   

       thumb_McpZ  thumb_IpX  thumb_IpY  thumb_IpZ  ...  pinky_McpZ  \
0       -0.106398   0.074692  -0.068785  -0.142921  ...   -0.064073   
1       -0.073063   0.078502   0.114953  -0.095067  ...   -0.036311   
2       -0.066864   0.050212  -0.017486  -0.090766  ...   -0.038240   
3       -0.074517  -0.016474  -0.055463  -0.104441  ...   -0.065722   
4       -0.067909  -0.048625   0.020722  -0.099847  ...   -0.075323   
...           ...        ...        ...        ...  ...         ...   
67799   -0.131472   0.127146  -0.123757  -0.168837  ...   -0.055269   
67800   -0.123317   0.137984  -0.119332  -0.158321  ...   -0.053041   
67801   -0.128762   0.150054  -0.123138  -0.164140  ...   -0.047751   
67802   -0.111925   0.163746  -0.121318  -0.144134  ...   -0.048661   
67803   -0.101427   0.168878  -0.128819  -0.132071  ...   -0.052191   

       pinky_PipX  pinky_PipY  pinky_PipZ  pinky_DipX  pinky_DipY  pinky_DipZ  \
0        0.047597    0.140222   -0.112481    0.002290    0.150317   -0.113498   
1        0.146225    0.066923   -0.077426    0.095178    0.085296   -0.079550   
2        0.072913    0.145718   -0.060053    0.033503    0.142184   -0.054022   
3        0.005305    0.114482   -0.091320   -0.034522    0.107430   -0.085204   
4        0.004712    0.040441   -0.102086   -0.038587    0.040920   -0.095680   
...           ...         ...         ...         ...         ...         ...   
67799    0.258377    0.045713   -0.112184    0.214903    0.069131   -0.127259   
67800    0.255173    0.055392   -0.112103    0.205787    0.079245   -0.126711   
67801    0.265978    0.047925   -0.109912    0.217237    0.072421   -0.128454   
67802    0.267293    0.056069   -0.107717    0.217863    0.077874   -0.123412   
67803    0.270327    0.060239   -0.105540    0.223794    0.077103   -0.116620   

       pinky_TipX  pinky_TipY  pinky_TipZ  
0       -0.044463    0.142457   -0.103716  
1        0.053499    0.083453   -0.070508  
2        0.006033    0.127925   -0.042074  
3       -0.059853    0.092084   -0.074993  
4       -0.068013    0.034524   -0.085842  
...           ...         ...         ...  
67799    0.162459    0.076754   -0.126205  
67800    0.148834    0.086681   -0.124629  
67801    0.159365    0.081097   -0.128880  
67802    0.161029    0.083968   -0.121660  
67803    0.171071    0.079793   -0.111782  

[67804 rows x 61 columns]

In [3]:
#取標籤
label = df["class"]
label

0        0
1        0
2        0
3        0
4        0
        ..
67799    4
67800    4
67801    4
67802    4
67803    4
Name: class, Length: 67804, dtype: int64

In [4]:
#取出特徵
data = df.iloc[:,1:]
data

thumb_CmcX  thumb_CmcY  thumb_CmcZ  thumb_McpX  thumb_McpY  thumb_McpZ  \
0        0.012261   -0.054713   -0.064790    0.046395   -0.081590   -0.106398   
1        0.007954    0.036694   -0.046014    0.047087    0.081199   -0.073063   
2        0.027219   -0.034373   -0.038773    0.057681   -0.044289   -0.066864   
3        0.000680   -0.036950   -0.039803    0.003148   -0.064025   -0.074517   
4       -0.016134    0.008927   -0.033502   -0.027797    0.014595   -0.067909   
...           ...         ...         ...         ...         ...         ...   
67799    0.010705   -0.060853   -0.083056    0.061441   -0.111522   -0.131472   
67800    0.016457   -0.060712   -0.078067    0.070719   -0.108737   -0.123317   
67801    0.019741   -0.062684   -0.082820    0.080508   -0.111906   -0.128762   
67802    0.027326   -0.065210   -0.071695    0.092318   -0.112928   -0.111925   
67803    0.029301   -0.069099   -0.064884    0.096214   -0.119432   -0.101427   

       thumb_IpX  thumb_IpY  thumb_IpZ  thumb_TipX  ...  pinky_McpZ  \
0       0.074692  -0.068785  -0.142921    0.106012  ...   -0.064073   
1       0.078502   0.114953  -0.095067    0.093199  ...   -0.036311   
2       0.050212  -0.017486  -0.090766    0.024275  ...   -0.038240   
3      -0.016474  -0.055463  -0.104441   -0.044202  ...   -0.065722   
4      -0.048625   0.020722  -0.099847   -0.069649  ...   -0.075323   
...          ...        ...        ...         ...  ...         ...   
67799   0.127146  -0.123757  -0.168837    0.201177  ...   -0.055269   
67800   0.137984  -0.119332  -0.158321    0.210252  ...   -0.053041   
67801   0.150054  -0.123138  -0.164140    0.224890  ...   -0.047751   
67802   0.163746  -0.121318  -0.144134    0.236523  ...   -0.048661   
67803   0.168878  -0.128819  -0.132071    0.240676  ...   -0.052191   

       pinky_PipX  pinky_PipY  pinky_PipZ  pinky_DipX  pinky_DipY  pinky_DipZ  \
0        0.047597    0.140222   -0.112481    0.002290    0.150317   -0.113498   
1        0.146225    0.066923   -0.077426    0.095178    0.085296   -0.079550   
2        0.072913    0.145718   -0.060053    0.033503    0.142184   -0.054022   
3        0.005305    0.114482   -0.091320   -0.034522    0.107430   -0.085204   
4        0.004712    0.040441   -0.102086   -0.038587    0.040920   -0.095680   
...           ...         ...         ...         ...         ...         ...   
67799    0.258377    0.045713   -0.112184    0.214903    0.069131   -0.127259   
67800    0.255173    0.055392   -0.112103    0.205787    0.079245   -0.126711   
67801    0.265978    0.047925   -0.109912    0.217237    0.072421   -0.128454   
67802    0.267293    0.056069   -0.107717    0.217863    0.077874   -0.123412   
67803    0.270327    0.060239   -0.105540    0.223794    0.077103   -0.116620   

       pinky_TipX  pinky_TipY  pinky_TipZ  
0       -0.044463    0.142457   -0.103716  
1        0.053499    0.083453   -0.070508  
2        0.006033    0.127925   -0.042074  
3       -0.059853    0.092084   -0.074993  
4       -0.068013    0.034524   -0.085842  
...           ...         ...         ...  
67799    0.162459    0.076754   -0.126205  
67800    0.148834    0.086681   -0.124629  
67801    0.159365    0.081097   -0.128880  
67802    0.161029    0.083968   -0.121660  
67803    0.171071    0.079793   -0.111782  

[67804 rows x 60 columns]

In [5]:
#資料標準化
scaler = MinMaxScaler(feature_range=(0,1))
data = scaler.fit_transform(data)
data

array([[0.46457903, 0.39362856, 0.38477537, ..., 0.43479194, 0.56737464,
        0.46266341],
       [0.45563931, 0.58927377, 0.41518598, ..., 0.50781681, 0.49988148,
        0.49738491],
       [0.49562819, 0.4371641 , 0.42691313, ..., 0.47243402, 0.55075176,
        0.52711547],
       ...,
       [0.48010652, 0.37656782, 0.35557279, ..., 0.58673291, 0.49718664,
        0.43635204],
       [0.49585124, 0.37116193, 0.37359055, ..., 0.58797345, 0.50047009,
        0.4439007 ],
       [0.49995094, 0.36283737, 0.38462268, ..., 0.59545924, 0.49569457,
        0.45422963]])

In [6]:
#分割資料
#把資料轉numpy
reshaped_data = np.array(data)
reshaped_label = np.array(label)

#將資料分為8:2
train_feature, test_feature, train_label, test_label = train_test_split(reshaped_data, reshaped_label, test_size=0.2, random_state = 42)

# split_boundary = int(reshaped_data.shape[0]*0.8)
# train_feature = reshaped_data[: split_boundary]
# test_feature = reshaped_data[split_boundary:]
# train_label = reshaped_label[: split_boundary]
# test_label = reshaped_label[split_boundary:]
print("訓練資料:", train_feature)
print("測試資料:", test_feature)
print("訓練資料數量:", len(train_feature))
print("測試資料數量:", len(test_feature))
print("訓練資料維度:", train_feature.shape)
print("測試資料維度:", test_feature.shape)

訓練資料: [[0.54566103 0.21337827 0.40272997 ... 0.63628521 0.43516734 0.49671951]
 [0.63680716 0.37062535 0.31159224 ... 0.79987026 0.55728958 0.50565753]
 [0.52302383 0.21818047 0.3770666  ... 0.63513922 0.45652825 0.48384773]
 ...
 [0.50660237 0.32122133 0.39097512 ... 0.58775343 0.40490925 0.5076494 ]
 [0.68575969 0.43355607 0.35627276 ... 0.65761792 0.48565171 0.68436813]
 [0.31465206 0.44823861 0.32598393 ... 0.49372636 0.55572769 0.41907353]]
測試資料: [[0.77464778 0.68642032 0.40871374 ... 0.73597174 0.50557424 0.82403886]
 [0.4253492  0.34172987 0.34126865 ... 0.54829664 0.45926468 0.46067337]
 [0.46009315 0.34146209 0.35006043 ... 0.63247522 0.53125767 0.40936174]
 ...
 [0.60089562 0.43713826 0.27497122 ... 0.58983913 0.4993357  0.55218073]
 [0.57177451 0.35372286 0.33369181 ... 0.60139093 0.47235676 0.54872777]
 [0.58223886 0.55266953 0.30574679 ... 0.60046567 0.61895727 0.58737091]]
訓練資料數量: 54243
測試資料數量: 13561
訓練資料維度: (54243, 60)
測試資料維度: (13561, 60)


In [7]:
train_label = np_utils.to_categorical(train_label)
test_label= np_utils.to_categorical(test_label)
print("訓練標籤:",train_label.shape)
print("測試標籤:",test_label.shape)

訓練標籤: (54243, 5)
測試標籤: (13561, 5)


In [8]:
#更改資料維度
train_feature = np.reshape(train_feature, (train_feature.shape[0], train_feature.shape[1], 1))
test_feature = np.reshape(test_feature, (test_feature.shape[0], test_feature.shape[1], 1))
print("訓練資料維度:", train_feature.shape)
print("測試資料維度:", test_feature.shape)

訓練資料維度: (54243, 60, 1)
測試資料維度: (13561, 60, 1)


In [9]:
#訓練模型
model = Sequential()
n = 0.2
model.add(Dense(units=32, input_dim=60, activation='relu'))    #輸入60個特徵
model.add(Dropout(n))
model.add(Dense(units=64, activation='relu'))
model.add(Dropout(n))
model.add(Dense(units=128, activation='relu'))
model.add(Dropout(n))
model.add(Dense(units=256, activation='relu'))
model.add(Dropout(n))
model.add(Dense(units=5, activation='softmax'))   #輸出為5個分類
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                1952      
                                                                 
 dropout (Dropout)           (None, 32)                0         
                                                                 
 dense_1 (Dense)             (None, 64)                2112      
                                                                 
 dropout_1 (Dropout)         (None, 64)                0         
                                                                 
 dense_2 (Dense)             (None, 128)               8320      
                                                                 
 dropout_2 (Dropout)         (None, 128)               0         
                                                                 
 dense_3 (Dense)             (None, 256)               3

In [10]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
fitmodel = model.fit(x=train_feature, y=train_label, validation_split=0.2, epochs=40, batch_size=20, verbose=2)
score = model.evaluate(x=test_feature, y=test_label, verbose=2)
print('\n測試資料準確率:', score[1])

Epoch 1/40
2170/2170 - 26s - loss: 1.0192 - accuracy: 0.5378 - val_loss: 0.7207 - val_accuracy: 0.6934 - 26s/epoch - 12ms/step
Epoch 2/40
2170/2170 - 23s - loss: 0.8036 - accuracy: 0.6492 - val_loss: 0.6573 - val_accuracy: 0.7451 - 23s/epoch - 10ms/step
Epoch 3/40
2170/2170 - 23s - loss: 0.7564 - accuracy: 0.6723 - val_loss: 0.6538 - val_accuracy: 0.7226 - 23s/epoch - 10ms/step
Epoch 4/40
2170/2170 - 23s - loss: 0.7201 - accuracy: 0.6935 - val_loss: 0.6232 - val_accuracy: 0.7331 - 23s/epoch - 10ms/step
Epoch 5/40
2170/2170 - 23s - loss: 0.6864 - accuracy: 0.7089 - val_loss: 0.5564 - val_accuracy: 0.7856 - 23s/epoch - 11ms/step
Epoch 6/40
2170/2170 - 23s - loss: 0.7000 - accuracy: 0.7045 - val_loss: 0.5838 - val_accuracy: 0.7566 - 23s/epoch - 10ms/step
Epoch 7/40
2170/2170 - 23s - loss: 0.6710 - accuracy: 0.7173 - val_loss: 0.5509 - val_accuracy: 0.7717 - 23s/epoch - 10ms/step
Epoch 8/40
2170/2170 - 23s - loss: 0.6611 - accuracy: 0.7248 - val_loss: 0.5443 - val_accuracy: 0.7783 - 23s/ep

In [11]:
model.save('DNN_origin_1.h5')