In [7]:
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Dropout
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [8]:
#載入資料
df = pd.read_csv('./output3.csv', encoding='utf-8')
df

class  thumb_CmcX  thumb_CmcY  thumb_CmcZ  thumb_McpX  thumb_McpY  \
0         0    0.013346   -0.078824   -0.093423    0.031121   -0.122133   
1         0    0.027224   -0.044876   -0.043898    0.058716   -0.081201   
2         0   -0.003453    0.058013   -0.038275    0.007701    0.082564   
3         0    0.011858   -0.065664   -0.090578    0.034992   -0.107807   
4         0    0.024853   -0.048601   -0.048028    0.050411   -0.086527   
...     ...         ...         ...         ...         ...         ...   
2395      4    0.087769   -0.083317   -0.123434    0.223958   -0.141625   
2396      4    0.087530   -0.084018   -0.124042    0.224004   -0.141430   
2397      4    0.089054   -0.083134   -0.123580    0.226646   -0.140727   
2398      4    0.086872   -0.086468   -0.119830    0.224556   -0.147392   
2399      4    0.092354   -0.084793   -0.120138    0.228880   -0.145291   

      thumb_McpZ  thumb_IpX  thumb_IpY  thumb_IpZ  ...  pinky_McpZ  \
0      -0.160828   0.008913  -0.113420  -0.211022  ...   -0.146264   
1      -0.078251   0.055767  -0.074666  -0.108053  ...   -0.089761   
2      -0.066121   0.003853   0.067236  -0.087953  ...   -0.064716   
3      -0.156370   0.007863  -0.092267  -0.208585  ...   -0.136011   
4      -0.089649   0.039719  -0.073551  -0.126198  ...   -0.110127   
...          ...        ...        ...        ...  ...         ...   
2395   -0.162112   0.367076  -0.153674  -0.186912  ...    0.075132   
2396   -0.162613   0.368180  -0.151960  -0.186628  ...    0.074654   
2397   -0.160776   0.373021  -0.152197  -0.183476  ...    0.080350   
2398   -0.155445   0.370444  -0.160861  -0.177185  ...    0.076444   
2399   -0.154909   0.371848  -0.158399  -0.175970  ...    0.085546   

      pinky_PipX  pinky_PipY  pinky_PipZ  pinky_DipX  pinky_DipY  pinky_DipZ  \
0      -0.093332    0.077454   -0.197066   -0.100144    0.039600   -0.197679   
1      -0.011452    0.085340   -0.123443   -0.016239    0.053635   -0.115443   
2       0.008161   -0.042829   -0.089203   -0.002254   -0.042870   -0.089281   
3      -0.061092    0.088679   -0.195662   -0.074918    0.046089   -0.193745   
4      -0.028435    0.078580   -0.158202   -0.026730    0.049350   -0.147598   
...          ...         ...         ...         ...         ...         ...   
2395    0.381167    0.075988   -0.000648    0.312193    0.103831   -0.022108   
2396    0.380460    0.073042   -0.001286    0.311100    0.102663   -0.022503   
2397    0.390318    0.064977    0.001065    0.322054    0.096732   -0.025063   
2398    0.398872    0.058757    0.003347    0.331470    0.086044   -0.018344   
2399    0.391861    0.070059    0.014768    0.328397    0.095633   -0.010415   

      pinky_TipX  pinky_TipY  pinky_TipZ  
0      -0.074212    0.029099   -0.192775  
1       0.009828    0.048981   -0.101101  
2       0.021662   -0.038748   -0.085531  
3      -0.055045    0.027574   -0.181527  
4       0.008735    0.047540   -0.126619  
...          ...         ...         ...  
2395    0.228171    0.106552   -0.013169  
2396    0.226597    0.106378   -0.013375  
2397    0.235701    0.104159   -0.019352  
2398    0.248584    0.086654   -0.011977  
2399    0.245318    0.097858   -0.007473  

[2400 rows x 61 columns]

In [9]:
#取標籤
label = df["class"]
label

0       0
1       0
2       0
3       0
4       0
       ..
2395    4
2396    4
2397    4
2398    4
2399    4
Name: class, Length: 2400, dtype: int64

In [10]:
#取出特徵
data = df.iloc[:,1:]
data

thumb_CmcX  thumb_CmcY  thumb_CmcZ  thumb_McpX  thumb_McpY  thumb_McpZ  \
0       0.013346   -0.078824   -0.093423    0.031121   -0.122133   -0.160828   
1       0.027224   -0.044876   -0.043898    0.058716   -0.081201   -0.078251   
2      -0.003453    0.058013   -0.038275    0.007701    0.082564   -0.066121   
3       0.011858   -0.065664   -0.090578    0.034992   -0.107807   -0.156370   
4       0.024853   -0.048601   -0.048028    0.050411   -0.086527   -0.089649   
...          ...         ...         ...         ...         ...         ...   
2395    0.087769   -0.083317   -0.123434    0.223958   -0.141625   -0.162112   
2396    0.087530   -0.084018   -0.124042    0.224004   -0.141430   -0.162613   
2397    0.089054   -0.083134   -0.123580    0.226646   -0.140727   -0.160776   
2398    0.086872   -0.086468   -0.119830    0.224556   -0.147392   -0.155445   
2399    0.092354   -0.084793   -0.120138    0.228880   -0.145291   -0.154909   

      thumb_IpX  thumb_IpY  thumb_IpZ  thumb_TipX  ...  pinky_McpZ  \
0      0.008913  -0.113420  -0.211022   -0.008307  ...   -0.146264   
1      0.055767  -0.074666  -0.108053    0.056937  ...   -0.089761   
2      0.003853   0.067236  -0.087953   -0.004198  ...   -0.064716   
3      0.007863  -0.092267  -0.208585   -0.020125  ...   -0.136011   
4      0.039719  -0.073551  -0.126198    0.039590  ...   -0.110127   
...         ...        ...        ...         ...  ...         ...   
2395   0.367076  -0.153674  -0.186912    0.488648  ...    0.075132   
2396   0.368180  -0.151960  -0.186628    0.491577  ...    0.074654   
2397   0.373021  -0.152197  -0.183476    0.497397  ...    0.080350   
2398   0.370444  -0.160861  -0.177185    0.494637  ...    0.076444   
2399   0.371848  -0.158399  -0.175970    0.494402  ...    0.085546   

      pinky_PipX  pinky_PipY  pinky_PipZ  pinky_DipX  pinky_DipY  pinky_DipZ  \
0      -0.093332    0.077454   -0.197066   -0.100144    0.039600   -0.197679   
1      -0.011452    0.085340   -0.123443   -0.016239    0.053635   -0.115443   
2       0.008161   -0.042829   -0.089203   -0.002254   -0.042870   -0.089281   
3      -0.061092    0.088679   -0.195662   -0.074918    0.046089   -0.193745   
4      -0.028435    0.078580   -0.158202   -0.026730    0.049350   -0.147598   
...          ...         ...         ...         ...         ...         ...   
2395    0.381167    0.075988   -0.000648    0.312193    0.103831   -0.022108   
2396    0.380460    0.073042   -0.001286    0.311100    0.102663   -0.022503   
2397    0.390318    0.064977    0.001065    0.322054    0.096732   -0.025063   
2398    0.398872    0.058757    0.003347    0.331470    0.086044   -0.018344   
2399    0.391861    0.070059    0.014768    0.328397    0.095633   -0.010415   

      pinky_TipX  pinky_TipY  pinky_TipZ  
0      -0.074212    0.029099   -0.192775  
1       0.009828    0.048981   -0.101101  
2       0.021662   -0.038748   -0.085531  
3      -0.055045    0.027574   -0.181527  
4       0.008735    0.047540   -0.126619  
...          ...         ...         ...  
2395    0.228171    0.106552   -0.013169  
2396    0.226597    0.106378   -0.013375  
2397    0.235701    0.104159   -0.019352  
2398    0.248584    0.086654   -0.011977  
2399    0.245318    0.097858   -0.007473  

[2400 rows x 60 columns]

In [11]:
#資料標準化
scaler = MinMaxScaler(feature_range=(0,1))
data = scaler.fit_transform(data)
data

array([[0.49973163, 0.22786676, 0.55170312, ..., 0.16308802, 0.23888771,
        0.45442743],
       [0.54923375, 0.32352123, 0.72850808, ..., 0.25361649, 0.27540392,
        0.61618471],
       [0.43981084, 0.61342807, 0.74857955, ..., 0.26636423, 0.11427318,
        0.64365759],
       ...,
       [0.76978194, 0.21572325, 0.44404341, ..., 0.49692914, 0.37674723,
        0.76042918],
       [0.7619994 , 0.20632836, 0.4574298 , ..., 0.51080663, 0.34459708,
        0.7734418 ],
       [0.78155122, 0.21104764, 0.45633027, ..., 0.50728868, 0.36517511,
        0.78139046]])

In [13]:
#分割資料
#把資料轉numpy
reshaped_data = np.array(data)
reshaped_label = np.array(label)
#將資料分為8:2

train_feature, test_feature, train_label, test_label = train_test_split(reshaped_data, reshaped_label, test_size=0.2, random_state = 42)

# split_boundary = int(reshaped_data.shape[0]*0.8)
# train_feature = reshaped_data[: split_boundary]
# test_feature = reshaped_data[split_boundary:]
# train_label = reshaped_label[: split_boundary]
# test_label = reshaped_label[split_boundary:]
print("測試資料:", train_feature)
print("訓練資料:", test_feature)
print("測試資料數量:", len(train_feature))
print("訓練資料數量:", len(test_feature))
print("測試資料維度:", train_feature.shape)
print("訓練資料維度:", test_feature.shape)

測試資料: [[0.60982746 0.22811725 0.29807732 ... 0.46093814 0.41651713 0.68509051]
 [0.53245084 0.05218502 0.66536358 ... 0.44725741 0.2717062  0.78354406]
 [0.37222401 0.33702341 0.40713484 ... 0.43037137 0.35998295 0.58960868]
 ...
 [0.67942153 0.24020491 0.61414522 ... 0.53919872 0.36972466 0.52081467]
 [0.18129541 0.64796213 0.34637455 ... 0.32577263 0.87340229 0.44482481]
 [0.62351861 0.27435454 0.55824799 ... 0.52659808 0.3707709  0.6034144 ]]
訓練資料: [[0.37731269 0.33279571 0.49374263 ... 0.48148919 0.34017201 0.56818227]
 [0.41929686 0.31990099 0.5316593  ... 0.51510006 0.3893796  0.56490161]
 [0.62557666 0.27275888 0.56293949 ... 0.49188671 0.3708506  0.58011548]
 ...
 [0.52320502 0.05682906 0.69383174 ... 0.44189989 0.31522659 0.78897961]
 [0.17058338 0.92359692 0.8000311  ... 0.44802427 0.69215549 0.77053641]
 [0.58068486 0.28518773 0.55577838 ... 0.5062783  0.37535504 0.60400083]]
測試資料數量: 1920
訓練資料數量: 480
測試資料維度: (1920, 60)
訓練資料維度: (480, 60)


In [14]:
#將訓練資料打散


In [15]:
train_label = np_utils.to_categorical(train_label)
test_label= np_utils.to_categorical(test_label)
print("訓練標籤:",train_label.shape)
print("測試標籤:",test_label.shape)

訓練標籤: (1920, 5)
測試標籤: (480, 5)


In [16]:
#更改資料維度
train_feature = np.reshape(train_feature, (train_feature.shape[0], train_feature.shape[1], 1))
test_feature = np.reshape(test_feature, (test_feature.shape[0], test_feature.shape[1], 1))
print("測試資料維度:", train_feature.shape)
print("訓練資料維度:", test_feature.shape)

測試資料維度: (1920, 60, 1)
訓練資料維度: (480, 60, 1)


In [17]:
#訓練模型
model = Sequential()
n = 0.2
model.add(Dense(units=32, input_dim=60, activation='relu'))    #輸入60個特徵
model.add(Dropout(n))
model.add(Dense(units=64, activation='relu'))
model.add(Dropout(n))
model.add(Dense(units=128, activation='relu'))
model.add(Dropout(n))
model.add(Dense(units=256, activation='relu'))
model.add(Dropout(n))
model.add(Dense(units=5, activation='softmax'))   #輸出為5個分類
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                1952      
                                                                 
 dropout (Dropout)           (None, 32)                0         
                                                                 
 dense_1 (Dense)             (None, 64)                2112      
                                                                 
 dropout_1 (Dropout)         (None, 64)                0         
                                                                 
 dense_2 (Dense)             (None, 128)               8320      
                                                                 
 dropout_2 (Dropout)         (None, 128)               0         
                                                                 
 dense_3 (Dense)             (None, 256)               3

In [18]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
fitmodel = model.fit(x=train_feature, y=train_label, validation_split=0.2, epochs=40, batch_size=20, verbose=2)
score = model.evaluate(x=test_feature, y=test_label, verbose=2)
print('\n測試資料準確率:', score[1])

Epoch 1/40
77/77 - 2s - loss: 1.3503 - accuracy: 0.4043 - val_loss: 1.0032 - val_accuracy: 0.5547 - 2s/epoch - 21ms/step
Epoch 2/40
77/77 - 0s - loss: 0.9297 - accuracy: 0.5618 - val_loss: 0.7613 - val_accuracy: 0.7370 - 402ms/epoch - 5ms/step
Epoch 3/40
77/77 - 0s - loss: 0.6977 - accuracy: 0.6888 - val_loss: 0.5257 - val_accuracy: 0.8385 - 391ms/epoch - 5ms/step
Epoch 4/40
77/77 - 0s - loss: 0.5077 - accuracy: 0.7982 - val_loss: 0.3311 - val_accuracy: 0.9141 - 396ms/epoch - 5ms/step
Epoch 5/40
77/77 - 0s - loss: 0.4202 - accuracy: 0.8392 - val_loss: 0.2474 - val_accuracy: 0.9219 - 401ms/epoch - 5ms/step
Epoch 6/40
77/77 - 0s - loss: 0.3314 - accuracy: 0.8776 - val_loss: 0.1940 - val_accuracy: 0.9401 - 409ms/epoch - 5ms/step
Epoch 7/40
77/77 - 0s - loss: 0.2772 - accuracy: 0.8926 - val_loss: 0.1672 - val_accuracy: 0.9479 - 425ms/epoch - 6ms/step
Epoch 8/40
77/77 - 0s - loss: 0.2617 - accuracy: 0.8997 - val_loss: 0.1084 - val_accuracy: 0.9661 - 428ms/epoch - 6ms/step
Epoch 9/40
77/77 -